SELECT SUM(CAST(DURATION_SECONDS as BIGINT)) as Duration, 
COUNT(ERROR_MESSAGE) as [Total Error],
MAX(ERROR_TYPE) as [Error Type],
TRIM(ERROR_MESSAGE) as [Error Message]
FROM dbo.FMDS_ERRORS 
GROUP BY ERROR_MESSAGE 
ORDER BY  [Total Error] DESC 